### ISSUE TITLE
Inconsistent spacing and indentation

### ISSUE THREAD

**Issue by 21stPhenom** [oscar-starks/TasksApp#2]
The indentation and placement of curly braces in some of the files are not consistent. This makes it a bit difficult to read, as one would have to manually match an ending curly brace to the starting one in order to understand what's in a certain block.

Try and ensure that your curly braces are indented properly, and other statements that should have whitespaces are spaced well.

**Comment by tech-priest-oscar** [comment]
I've modified the code, please do well to check the last commit and if you still have an issue, do well to raise it
